name: 'OpenTTD - Create Deployments'
description: 'Easy wrapper around GitHub Deployments API, to create a new deployment'
author: 'OpenTTD'
inputs:
  ref:
    description: 'Ref that is linked to this deployment; use a SHA-hash'
    required: true
  environment:
    description: 'Environment of this deployment'
    required: true
  version:
    description: 'Version of the Docker image'
    required: true
  date:
    description: 'Date of the Docker image'
    required: true
  docker-tag:
    description: 'Tag of the Docker image as on remote repository'
    required: true
  github-token:
    description: 'GitHub Token; cannot be the GITHUB_TOKEN, as that token cannot trigger another workflow'
    required: true

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo '{
          "ref": "${{ inputs.ref }}",
          "environment": "${{ inputs.environment }}",
          "description": "${{ inputs.version }} on ${{ inputs.date }}",
          "auto_merge": false,
          "required_contexts": [],
          "payload": {
            "tag": "${{ inputs.docker-tag }}",
            "version": "${{ inputs.version }}",
            "date": "${{ inputs.date }}"
          }
        }' > payload.json

      curl --fail \
        -X POST \
        -H "Authorization: token ${{ inputs.github-token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Accept: application/vnd.github.ant-man-preview+json" \
        -H "Accept: application/vnd.github.flash-preview+json" \
        https://api.github.com/repos/${{ github.repository }}/deployments \
        -d @payload.json
