name: 'OpenTTD - Build Docker'
description: 'Easy wrapper around Docker; needs to be used in combination with docker-vars and docker-publish'
author: 'OpenTTD'
inputs:
  registry:
    description: 'Registry to use for Docker images (default=Docker Hub)'
    default: docker.io
  name:
    description: 'Name of the Docker repository to use'
    required: true
  tag:
    description: 'Main tag of the Docker image'
    required: true
  tags:
    description: 'List of additional tags of the Docker image'
    required: true
  version:
    description: 'Version of the Docker image'
    required: true
  date:
    description: 'Date of the Docker image'
    required: true

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      REPO=${{ inputs.registry }}/${{ inputs.name }}

      docker build -t ${REPO}:${{ inputs.tag }} --build-arg BUILD_DATE=${{ inputs.date }} --build-arg BUILD_VERSION=${{ inputs.version }} .

      IFS=' '
      for alias in ${{ inputs.tags }}; do
        docker tag ${REPO}:${{ inputs.tag }} ${REPO}:${alias}
        echo "Successfully tagged ${REPO}:${alias}"
      done
