name: 'OpenTTD - Build Docker'
description: 'Easy wrapper around Docker; needs to be used in combination with docker-vars and docker-publish'
author: 'OpenTTD'
inputs:
  registry:
    description: 'Registry to use for Docker images (default=Docker Hub)'
  name:
    description: 'Name of the Docker repository to use'
    required: true
  tag:
    description: 'Main tag of the Docker image'
    required: true
  tags:
    description: 'List of additional tags of the Docker image'
    required: true
  version:
    description: 'Version of the Docker image'
    required: true
  date:
    description: 'Date of the Docker image'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
