name: 'OpenTTD - Update Deployments'
description: 'Easy wrapper around GitHub Deployments API, to update the state'
author: 'OpenTTD'
inputs:
  state:
    description: 'New state of the deployment; one of the following: in_progress, success, failure'
    required: true
  url:
    description: 'URL where deployment will be available [state=success]'
  description:
    description: 'Description of the state change'
  github-token:
    description: 'GitHub Token; cannot be the GITHUB_TOKEN, as it has no access to the deployment'
    required: true

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      echo '{
          "state": "${{ inputs.state }}",
          "description": "${{ inputs.description }}",
          "environment_url": "${{ inputs.url }}"
        }' > payload.json

      curl --fail \
        -X POST \
        -H "Authorization: token ${{ inputs.github-token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Accept: application/vnd.github.ant-man-preview+json" \
        -H "Accept: application/vnd.github.flash-preview+json" \
        https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.event.deployment.id }}/statuses \
        -d @payload.json
