name: 'OpenTTD - Checkout'
description: 'Checkout action to get tags and submodules'
author: 'OpenTTD'
inputs:
  with-tags:
    description: 'should tags be checked out'
    default: false
  with-submodules:
    description: 'should submodules be checked out'
    default: false
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      if [ -n "${{ inputs.with-tags }}" ]; then
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      fi
      if [ -n "${{ inputs.with-submodules }}" ]; then
        AUTH_HEADER=$(git config --local --get http.https://github.com/.extraheader)
        git submodule sync --recursive
        git -c "http.extraheader=${AUTH_HEADER}" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      fi
