name: 'OpenTTD - Checkout'
description: 'Checkout action to get tags and submodules'
author: 'OpenTTD'
inputs:
  with-tags:
    description: 'should tags be checked out'
    default: false
  with-submodules:
    description: 'should submodules be checked out'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
