name: 'OpenTTD - Deploy to AWS'
description: 'Deploy a new version to AWS'
author: 'OpenTTD'
inputs:
  aws-access-key-id:
    description: 'The AWS_ACCESS_KEY_ID to use for all operations'
    required: true
  aws-secret-access-key:
    description: 'The AWS_SECRET_ACCESS_KEY to use for all operations'
    required: true
  aws-region:
    description: 'The AWS_REGION to use for all operations'
    required: true
  name:
    description: 'The name of the component to deploy'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
