name: 'OpenTTD - Deploy to AWS'
description: 'Deploy a new version to AWS'
author: 'OpenTTD'
inputs:
  aws_access_key_id:
    description: 'The AWS_ACCESS_KEY_ID to use for all operations'
  aws_secret_access_key:
    description: 'The AWS_SECRET_ACCESS_KEY to use for all operations'
  aws_region:
    description: 'The AWS_REGION to use for all operations'
  name:
    description: 'The name of the component to deploy'
runs:
  using: 'node12'
  main: 'index.js'
