name: 'OpenTTD - Vars for Docker'
description: 'Defines variables for docker-build and docker-publish'
author: 'OpenTTD'
inputs:
  repository:
    description: 'Repository on hub.docker.com to use'
    default: ${{ github.repository }}
  registry-username:
    description: 'Username to use for registry (if unset, this will be a dry-run)'
outputs:
  name:
    description: 'Name of the Docker repository to use'
  version:
    description: 'Version of the Docker image'
  date:
    description: 'Date of the Docker image'
  sha:
    description: 'Sha-hash of the code producing this Docker image'
  tag:
    description: 'Main tag of the Docker image'
  tags:
    description: 'List of additional tags of the Docker image'
  environment:
    description: 'Environment this Docker image should be deployed on'
  dry-run:
    description: 'Is this a dry-run?'
runs:
  using: 'node12'
  main: 'dist/index.js'
