name: Publish Docker image to GitHub Container Registry

on:
  workflow_call:
    inputs:
      context:
        description: Context folder to use for building the image
        default: '.'
        type: string
    outputs:
      version:
        description: The version of the image produced
        value: ${{ jobs.publish_image.outputs.version }}
      digest:
        description: The digest (sha256) of the image produced
        value: ${{ jobs.publish_image.outputs.digest }}

jobs:
  publish_image:
    name: GitHub Container Registry
    runs-on: ubuntu-latest

    concurrency: publish

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=dev
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Publish
      id: publish
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_VERSION=${{ steps.meta.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    outputs:
      version: ${{ steps.meta.outputs.version }}
      digest: ${{ steps.publish.outputs.digest }}
