name: Release (Docker + Nomad)

# A generic reusing workflow that releases a project that:
# - use Docker.
# - use Nomad.

on:
  workflow_call:
    inputs:
      service:
        description: Name of the service on Nomad
        required: true
        type: string
      source-root:
        description: Root location of the project (where Dockerfile is)
        default: .
        type: string
      url:
        description: URL of the service
        required: true
        type: string
    secrets:
      NOMAD_SERVICE_PROD_KEY:
        description: Secret key to deploy the production service
        required: true

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    uses: ./.github/workflows/rw-docker-build.yml
    with:
      source-root: ${{ inputs.source-root }}
      publish: true

  deploy:
    needs:
    - release

    name: Deploy
    uses: ./.github/workflows/rw-nomad-deploy.yml
    secrets:
      NOMAD_SERVICE_KEY: ${{ secrets.NOMAD_SERVICE_PROD_KEY }}
    with:
      environment: Production
      service: ${{ inputs.service }}
      url: ${{ inputs.url }}
      version: "@sha256:${{ needs.release.outputs.digest }}"
