name: Nomad Deploy

# Deploys a new version on Nomad.

on:
  workflow_call:
    inputs:
      environment:
        description: The GitHub environment to deploy to
        required: true
        type: string
      service:
        description: Name of the service to deploy
        required: true
        type: string
      url:
        description: URL of the deployment
        required: true
        type: string
      version:
        description: New version of the service to deploy
        required: true
        type: string
    secrets:
      NOMAD_SERVICE_KEY:
        description: Secret key to deploy services
        required: true

concurrency:
  group: nomad-deploy-${{ inputs.service }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}

    steps:
    - name: Deploy
      run: |
        curl --fail -L -s -N -X POST \
          -H "Content-Type: application/json" \
          -d '{"version":"${{ inputs.version }}"}' \
          https://nomad-service.openttd.org/deploy/${{ inputs.service }}/${{ secrets.NOMAD_SERVICE_KEY }}
