name: Black

# Runs the Black code formatter on Python files.

on:
  workflow_call:
    inputs:
      python-path:
        description: Path to check
        required: true
        type: string
      python-version:
        description: Python version
        required: true
        type: string

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version}}

    - name: Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        black -l 120 --check ${{ inputs.python-path }}
