name: Docker Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add Dockerfile
      run: |
        echo "FROM alpine" > Dockerfile
        echo "ARG BUILD_DATE=''" >> Dockerfile
        echo "ARG BUILD_VERSION=''" >> Dockerfile

    - name: Docker Build
      uses: ./docker-build
      with:
        registry: testrepo
        name: test
        tag: main
        tags: other second third
        version: 1.0.0
        date: 2021-01-01

    - name: Validate
      run: |
        if [ "$(docker images -a | grep "^testrepo/test" | wc -l)" != "4" ]; then
          exit 1
        fi
