name: AWS Deployment

on:
  push:
    branches:
    - main
  # Pull Requests can't access the secrets, so no way to test this.
  # pull_request:
  #   branches:
  #   - main

jobs:
  deploy:
    name: Test

    uses: ./.github/workflows/aws-deployment.yml
    with:
      is_staging: true
      name: Test
      url_production: https://github.com/OpenTTD/actions
      url_staging: https://github.com/OpenTTD/actions
      digest: ${{ github.sha }}  # Not actually the digest, but for testing this is fine.
      version: ${{ github.sha }}  # Not actually the version, but for testing this is fine.
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
