name: Publish Image

on:
  push:
    branches:
    - main
  # Pull Requests can't write to GHCR, so no way to test this.
  # pull_request:
  #   branches:
  #   - main

jobs:
  deploy:
    name: Test
    uses: ./.github/workflows/publish-image.yml
    with:
      context: ./test
