name: Deployments Create

on:
  push:
    branches:
    - main
  # Sadly, we cannot test this on a Pull Request. At least validate it after merge.

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deployments Create
      id: publish
      uses: ./deployments-create
      with:
        ref: ${{ github.sha }}
        environment: test
        version: ${{ github.sha }}
        date: 2021-01-01
        docker-tag: ${{ github.sha }}
        github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
